const ACTIONS = {
    SET_CHAMPIONS: "SET_CHAMPIONS",
    SET_ABILITY_CHAMPIONS_NAMES: "SET_ABILITY_CHAMPIONS_NAMES",
    SET_ABILITY_PICKED: "SET_ABILITY_PICKED",
    SET_ABILITY_CORRECT: "SET_ABILITY_CORRECT",
    SET_SPLASH_CHAMPIONS_NAMES: "SET_SPLASH_CHAMPIONS_NAMES",
    SET_SPLASH_PICKED: "SET_SPLASH_PICKED",
    SET_SPLASH_CORRECT: "SET_SPLASH_CORRECT",
    SET_SPLASH_ZOOM: "SET_SPLASH_ZOOM",
    SET_ROLLED_ABILITY_CHAMPION: "ROLLED_ABILITY_CHAMPION",
    SET_ROLLED_ABILITY_IMG: "ROLLED_ABILITY_IMG",
    SET_ROLLED_SPLASH_CHAMPION: "ROLLED_SPLASH_CHAMPION",
    SET_ROLLED_SPLASH_IMG: "ROLLED_SPLASH_IMG",
    INITIAL_CLASSIC: "INITIAL_CLASSIC",
    INITIAL_SPLASH: "INITIAL_SPLASH",
}

export { ACTIONS }